language: ruby
cache: bundler
before_install: gem update bundler
script: bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - rbx-2
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - redis-server
