language: ruby
cache: bundler
before_install: gem update bundler
script: bundle exec rake
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
services:
  - redis-server
